AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy an EC2 instance with parameters passed from Jenkins CI/CD pipeline.'

Parameters:
  KeyName:
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instance.'
    Type: AWS::EC2::KeyPair::KeyName

  ImageId:
    Description: 'The ID of the AMI to be used for the instance.'
    Type: String

  InstanceType:
    Description: 'EC2 instance type'
    Type: String
    Default: 't3.micro' # This default can be overridden by Jenkins.

  SecurityGroupId:
    Description: 'The ID of the security group to assign to the instance.'
    Type: AWS::EC2::SecurityGroup::Id

  SubnetId:
    Description: 'The ID of the subnet in which the instance will be launched.'
    Type: AWS::EC2::Subnet::Id

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      Tags:
      - Key: Name
        Value: 'CI-CD-EC2-Instance'

Outputs:
  InstanceId:
    Description: 'The Instance ID of the newly created EC2 instance.'
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: 'The public IP address of the EC2 instance.'
    Value: !GetAtt MyEC2Instance.PublicIp
